### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by slawiko** [KovchugoK/Educational-Practice#2]
@KovchugoK 

HTML:
- почитайте про атрибут type вообще и в частности для тэга <link>. Это важно.
- старайтесь форматировать код. В IDE обычно для этого есть удобные хоткеи.

Общее:
- не нашел фильтров. Решили не делать, или забыли?
- responsive совсем не responsive. Попробуйте открыть вашу страничку с мобильного телефона. Или, например, в Chrome Dev Tools откройте device toolbar и выберите какой-либо смартфон. Почитайте про media queries в CSS.

**Comment by KovchugoK** [comment]
А что вы имеете ввиду про атрибут type где его стоит применить?

**Comment by slawiko** [comment]
Если бы вы почитали про него, вы бы поняли где и зачем. 

`For embed, link, object, script, source, and style elements, the type attribute specifies the Internet media type (formerly known as MIME type).` [здесь](https://www.w3schools.com/tags/att_type.asp) например.

**Comment by KovchugoK** [comment]
исправлено responsive
